### ISSUE TITLE
Cannot compile project depending on http-date with stack

### ISSUE THREAD

**Issue by schoettl** [kazu-yamamoto/http-date#10]
I just upgraded my project with `stack init --force` to use the latest version of `time` (1.9.3).

Now, `stack build` fails with this error:
```
Received ExitFailure 1 when running
Raw command: /home/jakob/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/bin/ghc-pkg-8.6.5 register --force /home/jakob/.stack/snapshots/x86_64-linux-tinfo6/cc327b0c5fdef883eaf1c6540833da7857c3dd16d0eaf01f49af333dbfa999d5/8.6.5/pkgdb/http-date-0.0.8-1KXeOUVg3O2Bhxp274Seqs.conf
Standard output:

Reading package info from "/home/jakob/.stack/snapshots/x86_64-linux-tinfo6/cc327b0c5fdef883eaf1c6540833da7857c3dd16d0eaf01f49af333dbfa999d5/8.6.5/pkgdb/http-date-0.0.8-1KXeOUVg3O2Bhxp274Seqs.conf" ... done.
Standard error:

: invalid package identifier: 
: missing id field

Progress 4/87
```

The .conf file mentioned is empty. All other .conf files (other dependencies) are not empty and contain config like
```
name: http-client
version: 0.6.4
id: http-client-0.6.4-24Cd5mIgHrTK1iSdVqHybx
key: http-client-0.6.4-24Cd5mIgHrTK1iSdVqHybx
license: MIT
...
```

Do you have an idea what goes wrong?

Thank you!

**Comment by schoettl** [comment]
Work-around:

The error don't show up after I
- pasted the raw content of `http-date.cabal` into that .conf file
- and added lines `id: http-date` and `key: http-date`.

(I got other unrelated errors then and had to `rm -rf ~/.stack .stack-work` :/ )

**Comment by kazu-yamamoto** [comment]
I think that this issue should be discussed in the stack community. I don't know stack very well.

**Comment by schoettl** [comment]
I close this. Maybe it was just another weired stack problem. At the moment I cannot test because I even forgot which project it was, but it worked in the end.
