### ISSUE TITLE
Breakage due to inlinePerformIO removal in bytestring-0.11

### ISSUE THREAD

**Issue by sjakobi** [kazu-yamamoto/http-date#11]
This package will need a patch, and could also use some Hackage revisions to add `< 0.11` bounds for the existing versions.

See https://mail.haskell.org/pipermail/libraries/2020-September/030834.html regarding the `bytestring` changes.

**Comment by alexbiehl** [comment]
I think https://github.com/kazu-yamamoto/http-date/commit/29fb82303af877cff6e9651835b280a78de5e306 fixed the compatibility issues. All we need is another release.

**Comment by kazu-yamamoto** [comment]
Sorry for the delay.
I tested `bytestring` v0.11 two days ago but I could not link `http-date` to `bytestring` and was stacked.
I can release the next version without testing it by myself.
Please wait for a while.

**Comment by kazu-yamamoto** [comment]
A new version has been released.

**Comment by alexbiehl** [comment]
Thank you @kazu-yamamoto!!

**Comment by sjakobi** [comment]
Thanks! :)

Note that the new version doesn't build with GHC < 7.10: https://matrix.hackage.haskell.org/#/package/http-date/0.0.9/ghc-7.8.4@1600997793

**Comment by kazu-yamamoto** [comment]
I think this has been fixed in v0.0.10.
